/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include <iostream>

using namespace std;

int main ()
{
    long a = 1;
    long b = 1;
    long c = a + b;
    long sum = 0;
    while (c < 4000000)
    {
        sum += ((c%2==0)?c:0);
        a = b;
        b = c;
        c = a + b;
        //cout << a << " " << b << " " << c << " " << sum << endl;
    }
    cout << sum << endl;
}
